services:

  TwitterSpout:
    class: processor.TwitterSpout
    arguments:
      consumer_key: '%consumer_key%'
      consumer_secret: '%consumer_secret%'
      access_token: '%access_token%'
      access_token_secret: '%access_token_secret%'

  LogHandle:
    class: chains.log_handle.LogHandle
    arguments: ~

chains:
  - TwitterSpout
  - LogHandle